/* eslint-disable */
/**
 * Generated Convex API.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED by `npx convex dev`.
 * Run `npx convex dev` to regenerate.
 */
import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as users from "../users";

type FullApi = ApiFromModules<{
  users: typeof users;
}>;

// Runtime stub that creates nested function references on access.
// This will be replaced by the real generated file when `npx convex dev` runs.
function makeApi(path: string[] = []): any {
  return new Proxy({} as any, {
    get(_target, prop: string) {
      if (typeof prop === "string") {
        const newPath = [...path, prop];
        return makeApi(newPath);
      }
      return undefined;
    },
  });
}

export const api: FilterApi<FullApi, FunctionReference<any, "public">> =
  makeApi() as any;
export const internal: FilterApi<FullApi, FunctionReference<any, "internal">> =
  makeApi() as any;
