/* eslint-disable */
/**
 * Generated Convex API.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED by `npx convex dev`.
 * Run `npx convex dev` to regenerate.
 */
import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as users from "../users";
import type * as schoolEntries from "../schoolEntries";
import type * as homework from "../homework";
import type * as exams from "../exams";
import type * as classwork from "../classwork";
import type * as http from "../http";

type FullApi = ApiFromModules<{
  users: typeof users;
  schoolEntries: typeof schoolEntries;
  homework: typeof homework;
  exams: typeof exams;
  classwork: typeof classwork;
  http: typeof http;
}>;

// Runtime stub using Proxy for SSR compatibility.
// Replaced by real generated file when `npx convex dev` runs.
function makeApi(): any {
  return new Proxy({} as any, {
    get(_target, prop: string) {
      if (typeof prop === "string") {
        return makeApi();
      }
      return undefined;
    },
  });
}

export const api: FilterApi<FullApi, FunctionReference<any, "public">> =
  makeApi() as any;
export const internal: FilterApi<FullApi, FunctionReference<any, "internal">> =
  makeApi() as any;
