/* eslint-disable */
/**
 * Generated data model types.
 * THIS CODE IS AUTOMATICALLY GENERATED by `npx convex dev`.
 */
import type { DataModelFromSchemaDefinition } from "convex/server";
import type { GenericId } from "convex/values";
import type schema from "../schema";

export type DataModel = DataModelFromSchemaDefinition<typeof schema>;

export type Id<TableName extends keyof DataModel> = GenericId<TableName>;
