/* eslint-disable */
/**
 * Generated utilities for implementing server-side Convex query and mutation functions.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED by `npx convex dev`.
 * Run `npx convex dev` to regenerate.
 */
import {
  actionGeneric,
  httpActionGeneric,
  queryGeneric,
  mutationGeneric,
  internalActionGeneric,
  internalMutationGeneric,
  internalQueryGeneric,
} from "convex/server";
import type { DataModel } from "./dataModel";

export const query = queryGeneric as typeof queryGeneric & {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  (func: any): any;
};
export const internalQuery = internalQueryGeneric as typeof internalQueryGeneric;
export const mutation = mutationGeneric as typeof mutationGeneric & {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  (func: any): any;
};
export const internalMutation = internalMutationGeneric as typeof internalMutationGeneric;
export const action = actionGeneric as typeof actionGeneric;
export const internalAction = internalActionGeneric as typeof internalActionGeneric;
export const httpAction = httpActionGeneric as typeof httpActionGeneric;
